// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxvvuaezvxidtepzxztl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4dnZ1YWV6dnhpZHRlcHp4enRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDYzNTgsImV4cCI6MjA2MTkyMjM1OH0.frVYytGK-osy4_870K3GdmujHzqdGzsV8yNSmuCFZks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);